### ISSUE TITLE
cant get <p> to update totals

### ISSUE THREAD

**Issue by Zitterman** [Zitterman/three_card_monte#1]
var updateMoney = function() {
  var money = 0;
  var moneyHolder = $("#money-update p");
  var total = moneyHolder.text("$" + money);
  if (randomCard === cardArray[1]) {
    money = money + 20;
    return total;
  } else if (randomCard !== cardArray[1]) {
    money = money - 20;
    return total;
  }
};

**Comment by rapala61** [comment]
let's meet

**Comment by rapala61** [comment]
fixed in person
