### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Zitterman** [Zitterman/three_card_monte#3]
It randomizing the cards the first time but wont re-randomize.

var cardArray = ["joker", "queen", "joker"];

// Durstenfeld shuffle algorithm
function shuffleArray(array) {
  for (var i = array.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() \* (i + 1));
      var temp = array[i];
      array[i] = array[j];
      array[j] = temp;
  }
  return array;
};

for (i=cardArray.length; i > 0; i--){
    var shuffled = shuffleArray(cardArray);
  var newCard = shuffled.pop();
}

**Comment by carrafa** [comment]
_meeting in person_
